name: Docker Image CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ludeeus/action-shellcheck@1.1.0
    # - uses: hadolint/hadolint-action@v1.5.0
    - name: Login Registry
      uses: docker/login-action@v1
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - run: |
        docker buildx build --platform linux/arm64 -t ghcr.io/${{ env.GITHUB_ACTOR }}/github-actions-runner --push .
